// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPbEMdpNkjexk13h9LRCLopaEi9W9ewxI',
    appId: '1:561718595895:android:739532af15c7e5ec248ab2',
    messagingSenderId: '561718595895',
    projectId: 'drdental-5d61e',
    storageBucket: 'drdental-5d61e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc9qz6EL6vbtaC9RG9g4OtpzqRKyXisn0',
    appId: '1:561718595895:ios:2ee574c19f4f8241248ab2',
    messagingSenderId: '561718595895',
    projectId: 'drdental-5d61e',
    storageBucket: 'drdental-5d61e.firebasestorage.app',
    iosBundleId: 'com.example.drdental',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkj0hVTzyzAwMvU-vzZ9dw1JiScbPLT1k',
    appId: '1:561718595895:web:44649b7981c0ab49248ab2',
    messagingSenderId: '561718595895',
    projectId: 'drdental-5d61e',
    authDomain: 'drdental-5d61e.firebaseapp.com',
    storageBucket: 'drdental-5d61e.firebasestorage.app',
    measurementId: 'G-P1PJ9LRMLL',
  );
}
